// 行星数据文件
const PLANET_DATA = {
    sun: {
        name: "太阳",
        diameter: "1,392,700 公里",
        distance: "0",
        orbitPeriod: "N/A",
        rotationPeriod: "25.38 地球日",
        description: "太阳系的中心天体，占据了太阳系99.86%的质量。它是由氢和氦组成的热等离子体球体，通过核聚变产生巨大的能量。",
        texture: "textures/sun.jpg",
        size: 50,
        position: [0, 0, 0],
        rotationSpeed: 0.002,
        orbitSpeed: 0,
        orbitRadius: 0,
        emissive: true,
        emissiveColor: 0xffff80,
        emissiveIntensity: 0.6
    },
    mercury: {
        name: "水星",
        diameter: "4,879 公里",
        distance: "5,790万 公里",
        orbitPeriod: "88 地球日",
        rotationPeriod: "58.6 地球日",
        description: "太阳系最内侧且最小的行星，表面布满陨石坑。它没有大气层保护，温度变化极端。",
        texture: "textures/mercury.jpg",
        size: 3.8,
        position: [70, 0, 0],
        rotationSpeed: 0.004,
        orbitSpeed: 0.04,
        orbitRadius: 70
    },
    venus: {
        name: "金星",
        diameter: "12,104 公里",
        distance: "1.082亿 公里",
        orbitPeriod: "225 地球日",
        rotationPeriod: "243 地球日（逆转）",
        description: "被称为地球的姊妹星，因为大小相似。它被厚厚的二氧化碳大气层所覆盖，造成了极端的温室效应。",
        texture: "textures/venus.jpg",
        size: 9.5,
        position: [100, 0, 0],
        rotationSpeed: -0.002,  // 负值表示逆向自转
        orbitSpeed: 0.015,
        orbitRadius: 100
    },
    earth: {
        name: "地球",
        diameter: "12,756 公里",
        distance: "1.496亿 公里",
        orbitPeriod: "365.25 地球日",
        rotationPeriod: "23.93 小时",
        description: "太阳系中唯一已知存在生命的行星，拥有液态水和氮氧大气层。其表面约有71%被水覆盖。",
        texture: "textures/earth.jpg",
        size: 10,
        position: [150, 0, 0],
        rotationSpeed: 0.01,
        orbitSpeed: 0.01,
        orbitRadius: 150,
        hasMoon: true,
        moonData: {
            name: "月球",
            diameter: "3,475 公里",
            distance: "384,400 公里（距地球）",
            orbitPeriod: "27.3 地球日",
            rotationPeriod: "27.3 地球日（同步自转）",
            texture: "textures/moon.jpg",
            size: 2.7,
            orbitRadius: 15,
            orbitSpeed: 0.05,
            rotationSpeed: 0.01
        }
    },
    mars: {
        name: "火星",
        diameter: "6,779 公里",
        distance: "2.279亿 公里",
        orbitPeriod: "687 地球日",
        rotationPeriod: "24.6 小时",
        description: "被称为红色星球，表面有氧化铁沉积。拥有季节变化和极地冰盖，是人类未来可能殖民的目标。",
        texture: "textures/mars.jpg",
        size: 5.3,
        position: [210, 0, 0],
        rotationSpeed: 0.009,
        orbitSpeed: 0.008,
        orbitRadius: 210
    },
    jupiter: {
        name: "木星",
        diameter: "139,820 公里",
        distance: "7.785亿 公里",
        orbitPeriod: "11.86 地球年",
        rotationPeriod: "9.93 小时",
        description: "太阳系最大的行星，是一个气体巨星。它的大红斑是一个持续了至少400年的巨大风暴系统。",
        texture: "textures/jupiter.jpg",
        size: 30,
        position: [340, 0, 0],
        rotationSpeed: 0.04,
        orbitSpeed: 0.002,
        orbitRadius: 340
    },
    saturn: {
        name: "土星",
        diameter: "116,460 公里",
        distance: "14.3亿 公里",
        orbitPeriod: "29.46 地球年",
        rotationPeriod: "10.7 小时",
        description: "以其显著的环系统而闻名，主要由冰粒子和岩石碎片组成。是仅次于木星的第二大行星。",
        texture: "textures/saturn.jpg",
        ringTexture: "textures/saturn_rings.png",
        size: 25,
        position: [440, 0, 0],
        rotationSpeed: 0.038,
        orbitSpeed: 0.0009,
        orbitRadius: 440,
        hasRings: true,
        ringSize: 40
    },
    uranus: {
        name: "天王星",
        diameter: "50,724 公里",
        distance: "28.7亿 公里",
        orbitPeriod: "84.01 地球年",
        rotationPeriod: "17.2 小时（逆转）",
        description: "独特之处在于它的自转轴几乎平行于轨道平面，像是'侧躺'着公转。它是一个冰巨星，有淡蓝色的外观。",
        texture: "textures/uranus.jpg",
        size: 15,
        position: [520, 0, 0],
        rotationSpeed: -0.03,  // 负值表示逆向自转
        orbitSpeed: 0.0004,
        orbitRadius: 520
    },
    neptune: {
        name: "海王星",
        diameter: "49,244 公里",
        distance: "45亿 公里",
        orbitPeriod: "164.8 地球年",
        rotationPeriod: "16.1 小时",
        description: "太阳系最远的行星，是一个风暴活跃的冰巨星。以其深蓝色的外观和强大的风暴系统而著名。",
        texture: "textures/neptune.jpg",
        size: 14.5,
        position: [630, 0, 0],
        rotationSpeed: 0.032,
        orbitSpeed: 0.0001,
        orbitRadius: 630
    }
}; 